### ISSUE TITLE
Responsivness

### ISSUE THREAD

**Issue by Li-Kane** [cse110-sp24-group21/Warmup-Project#1]
Our website responsiveness needs to be setup. Here are a couple notes:
- Min-width of container is 480px, but phone screens can be smaller
- Task items can cause the container to expand if there is a lot of text, making it a bit chunky.

Responsiveness in having the container fill up the screen works fine, this is mainly issues practice

**Comment by Astraeven0502** [comment]
The task list box exceeds the frame when zooming in/out.
